name: CI-format-check

on:
  pull_request:
    branches: [master]    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  spotless:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Runs a single command using the runners shell
      - name: Run spotless checks on robot code
        working-directory: ./BragiCode
        run: ./gradlew spotlessCheck